-- ============================================
-- APP-RRHH Schedule — Supabase (PostgreSQL) Setup
-- ============================================
-- Run this in the Supabase SQL Editor

-- ============================================
-- 1. SHOPS
-- ============================================
CREATE TABLE IF NOT EXISTS shops (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  color VARCHAR(7) NOT NULL DEFAULT '#6366f1',
  active SMALLINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- 2. USERS (authentication)
-- ============================================
CREATE TABLE IF NOT EXISTS users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  email VARCHAR(255) DEFAULT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'staff' CHECK (role IN ('manager','staff')),
  employee_id INT DEFAULT NULL,
  active SMALLINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- 3. EMPLOYEES
-- ============================================
CREATE TABLE IF NOT EXISTS employees (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  phone VARCHAR(30) DEFAULT NULL,
  role VARCHAR(100) DEFAULT NULL,
  max_weekly_hours DECIMAL(5,2) NOT NULL DEFAULT 40.00,
  active SMALLINT NOT NULL DEFAULT 1,
  user_id INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Trigger to auto-update updated_at on employees
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_employees_updated_at ON employees;
CREATE TRIGGER trg_employees_updated_at
    BEFORE UPDATE ON employees
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- 4. AVAILABILITY (weekly schedule per employee)
-- ============================================
CREATE TABLE IF NOT EXISTS availability (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id INT NOT NULL,
  day_of_week SMALLINT NOT NULL, -- 0=Sunday, 1=Monday ... 6=Saturday
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_avail_employee ON availability(employee_id);
CREATE INDEX IF NOT EXISTS idx_avail_day ON availability(day_of_week);

-- ============================================
-- 5. SHIFTS
-- ============================================
CREATE TABLE IF NOT EXISTS shifts (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id INT DEFAULT NULL,
  is_unassigned SMALLINT DEFAULT 0,
  shop_id INT NOT NULL,
  shift_date DATE NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled','completed','cancelled')),
  notes TEXT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
  FOREIGN KEY (shop_id) REFERENCES shops(id) ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS trg_shifts_updated_at ON shifts;
CREATE TRIGGER trg_shifts_updated_at
    BEFORE UPDATE ON shifts
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX IF NOT EXISTS idx_shift_employee_date ON shifts(employee_id, shift_date);
CREATE INDEX IF NOT EXISTS idx_shift_shop_date ON shifts(shop_id, shift_date);
CREATE INDEX IF NOT EXISTS idx_shift_date ON shifts(shift_date);

-- ============================================
-- 6. SWAP REQUESTS (Release / Claim)
-- ============================================
CREATE TABLE IF NOT EXISTS swap_requests (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shift_id INT NOT NULL,
  target_shift_id INT DEFAULT NULL,
  requester_id INT NOT NULL,
  accepter_id INT DEFAULT NULL,
  claimer_id INT DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','accepted','approved','rejected','cancelled')),
  message TEXT DEFAULT NULL,
  manager_note TEXT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (shift_id) REFERENCES shifts(id) ON DELETE CASCADE,
  FOREIGN KEY (target_shift_id) REFERENCES shifts(id) ON DELETE SET NULL,
  FOREIGN KEY (requester_id) REFERENCES employees(id) ON DELETE CASCADE,
  FOREIGN KEY (accepter_id) REFERENCES employees(id) ON DELETE SET NULL,
  FOREIGN KEY (claimer_id) REFERENCES employees(id) ON DELETE SET NULL
);

DROP TRIGGER IF EXISTS trg_swap_requests_updated_at ON swap_requests;
CREATE TRIGGER trg_swap_requests_updated_at
    BEFORE UPDATE ON swap_requests
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX IF NOT EXISTS idx_swap_status ON swap_requests(status);
CREATE INDEX IF NOT EXISTS idx_swap_requester ON swap_requests(requester_id);

-- ============================================
-- 7. TIME OFF
-- ============================================
CREATE TABLE IF NOT EXISTS time_off (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id INT NOT NULL,
  date_from DATE NOT NULL,
  date_to DATE NOT NULL,
  type VARCHAR(20) NOT NULL DEFAULT 'unavailable' CHECK (type IN ('vacation','unavailable','sick','personal')),
  reason TEXT DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_timeoff_emp_dates ON time_off(employee_id, date_from, date_to);
CREATE INDEX IF NOT EXISTS idx_timeoff_dates ON time_off(date_from, date_to);

-- ============================================
-- 8. SEED DATA
-- ============================================

-- Shops
INSERT INTO shops (name, color) VALUES
  ('ChinaTown',  '#6366f1'),
  ('Entrance',   '#f59e0b'),
  ('GlobesHats', '#10b981');

-- Manager account (password: 1234)
INSERT INTO users (username, email, password_hash, role) VALUES
  ('manager', 'buchinisantiago@gmail.com', '$2y$10$zemeQSol2FVmR7NCvmcWxufuzIqX2uyjxEPFbSeo98m6Hvr2u0BSO', 'manager');

-- Staff accounts (password = username for each, e.g. staff1/staff1)
INSERT INTO users (username, password_hash, role) VALUES
  ('staff1',  '$2y$10$kv.whXBoStEaPhlbYebPgeaO42zQvUJmjjOpYFbimKZowEndbW6n2', 'staff'),
  ('staff2',  '$2y$10$/ee0i3uXpBWNw693X9LjqeEk0uMfCgAcIIJAq06SvBhoWYswcFdMi', 'staff'),
  ('staff3',  '$2y$10$TaQwrgFyAF1Pm0S6Y/VJ7eY1MpglMH5qN4bQolN9t3Z.pl8dZ5Bey', 'staff'),
  ('staff4',  '$2y$10$mDZOYMNbpaaVj/.jD2429.4JsdpeLtxAxm7MvS3NJcY6wwWsudyEK', 'staff'),
  ('staff5',  '$2y$10$SKiWJVYnwWVLtsdnTQqr7.wFtthHYc.Vh0YUHFCOc15MpqiV349v.', 'staff'),
  ('staff6',  '$2y$10$NrT78yUI9cIN2gAibr1twu1XOc.EYPvmd87gYeIkfMje1BqzXap0G', 'staff'),
  ('staff7',  '$2y$10$JOWZAuUAxLwH8i2jVCl98uVewB3MjCyFAdNr0EROSpBof7iEGcooS', 'staff'),
  ('staff8',  '$2y$10$BoM4ulnTJOTY1ThJAUGhKuRpYV80Ng17B5PmcckmnRUuDS7KjwxDe', 'staff'),
  ('staff9',  '$2y$10$Q4VJAoNQ54tVf5NHt6LYbOWE6e3UprGR2V4rbwCNndEUFXiGdQBT2', 'staff'),
  ('staff10', '$2y$10$m/9/HZjqY1kwXVKSoVn7xuF3xF7i43Zjc5QLtXVZoy0OS0t.wsLkC', 'staff');

